# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:orgtec}
    url: jdbc:mysql://${MYSQL-HOST:farm-mysql}:${MYSQL-PORT:3366}/${MYSQL-DB:farm}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

  # json全局序列化配置 驼峰命名 忽略 null
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 0)
      logic-delete-value: 0
      # 逻辑未删除值(默认为 1)
      logic-not-delete-value: 1



# Logger Config
logging:
  level:
    cn.orgtec.farm.mapper: debug